package pojos;
// Generated 09/07/2018 16:09:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int dni;
     private String nombre;
     private int vip;
     private Set<Carrito> carritos = new HashSet<Carrito>(0);

    public Usuario() {
    }

	
    public Usuario(int dni, int vip) {
        this.dni = dni;
        this.vip = vip;
    }
    public Usuario(int dni, String nombre, int vip, Set<Carrito> carritos) {
       this.dni = dni;
       this.nombre = nombre;
       this.vip = vip;
       this.carritos = carritos;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getVip() {
        return this.vip;
    }
    
    public void setVip(int vip) {
        this.vip = vip;
    }
    public Set<Carrito> getCarritos() {
        return this.carritos;
    }
    
    public void setCarritos(Set<Carrito> carritos) {
        this.carritos = carritos;
    }




}


