-- MySQL Script generated by MySQL Workbench
-- Mon Jul  9 15:52:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carritodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carritodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carritodb` DEFAULT CHARACTER SET utf8 ;
USE `carritodb` ;

-- -----------------------------------------------------
-- Table `carritodb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritodb`.`usuario` (
  `nombre` VARCHAR(45) NULL,
  `dni` INT NOT NULL,
  `vip` INT(1) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carritodb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritodb`.`carrito` (
  `idcarrito` INT NOT NULL AUTO_INCREMENT,
  `promo` INT(1) NOT NULL,
  `usuarioDni` INT NOT NULL,
  PRIMARY KEY (`idcarrito`),
  INDEX `fk_carrito_usuario1_idx` (`usuarioDni` ASC),
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuarioDni`)
    REFERENCES `carritodb`.`usuario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carritodb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritodb`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carritodb`.`carritoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritodb`.`carritoProducto` (
  `idcarrito` INT NOT NULL,
  `idproducto` INT NOT NULL,
  INDEX `fk_carrito_has_producto_producto1_idx` (`idproducto` ASC),
  INDEX `fk_carrito_has_producto_carrito_idx` (`idcarrito` ASC),
  PRIMARY KEY (`idcarrito`, `idproducto`),
  CONSTRAINT `fk_carrito_has_producto_carrito`
    FOREIGN KEY (`idcarrito`)
    REFERENCES `carritodb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_producto_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `carritodb`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
